### ISSUE TITLE
Closing xwayland windows in rootston segfaults

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#232]

**Comment by emersion** [comment]
```
xterm: fatal IO error 11 (Resource temporarily unavailable) or KillClient on X server ":5"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff70bacfa in __strcmp_sse2_unaligned () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff70bacfa in __strcmp_sse2_unaligned () at /usr/lib/libc.so.6
#1  0x00007ffff797b325 in  () at /usr/lib/libwayland-server.so.0
#2  0x00007ffff79761c5 in wl_resource_instance_of () at /usr/lib/libwayland-server.so.0
#3  0x00007ffff7977f9d in wl_shm_buffer_get () at /usr/lib/libwayland-server.so.0
#4  0x00007ffff7bb4f79 in wlr_surface_flush_damage (surface=0x5555560afbe0) at ../types/wlr_surface.c:456
#5  0x000055555555c4c8 in render_surface (surface=0x5555560afbe0, desktop=0x555555f619d0, wlr_output=0x555555f70970, when=0x7fffffffe068, lx=180, ly=175, rotation=0)
    at ../rootston/output.c:22
#6  0x000055555555c45c in render_view (view=0x5555560a6720, desktop=0x555555f619d0, wlr_output=0x555555f70970, when=0x7fffffffe068) at ../rootston/output.c:83
#7  0x000055555555c281 in output_frame_notify (listener=0x555556045100, data=0x555555f70970) at ../rootston/output.c:101
#8  0x00007ffff7ba3f0b in wl_signal_emit (signal=0x555555f70a50, data=0x555555f70970) at /usr/include/wayland-server-core.h:388
#9  0x00007ffff7ba4af3 in surface_frame_callback (data=0x555555f70970, cb=0x555556045670, time=34947392) at ../backend/wayland/output.c:23
#10 0x00007ffff4ae11c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#11 0x00007ffff4ae0c2a in ffi_call () at /usr/lib/libffi.so.6
#12 0x00007ffff6e25bad in  () at /usr/lib/libwayland-client.so.0
#13 0x00007ffff6e22679 in  () at /usr/lib/libwayland-client.so.0
#14 0x00007ffff6e239b4 in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#15 0x00007ffff7ba34a0 in dispatch_events (fd=4, mask=1, data=0x555555771310) at ../backend/wayland/backend.c:20
#16 0x00007ffff79789b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x00007ffff797714c in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x000055555555beb2 in main (argc=3, argv=0x7fffffffe798) at ../rootston/main.c:45
```

**Comment by acrisci** [comment]
I think this was fixed at some point because I can't reproduce it.

**Comment by emersion** [comment]
I can still reproduce it: it happens when you quit with the compositor keybinding (`close` command in the config).
